Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -54,10 +54,10 @@ jobs:
        - name: Deploy
          run: |
            docker compose up -d
-       - name: Clean Up
-         run: |
-           ls -la ./
-           rm -rf ./* || true
-           rm -rf ./.??* || true
-           ls -la ./
+       # - name: Clean Up
+       #   run: |
+       #     ls -la ./
+       #     rm -rf ./* || true
+       #     rm -rf ./.??* || true
+       #     ls -la ./
            
